// Generated by `doctrine boot install` — do not edit.
import { execSync } from "node:child_process";

let cachedBoot: string | null = null;

function resolveBoot(): string {
  try {
    return execSync("/nix/store/p4r89h46hvapyf300ab61312r4ha8a4z-doctrine-0.46.5/bin/doctrine prompt resolve --role orchestrator", {
      encoding: "utf-8",
      cwd: process.cwd(),
      timeout: 5_000,
    }).trimEnd();
  } catch (err) {
    console.error("[doctrine-boot] resolve failed:", err);
    return "";
  }
}

export default async function (pi) {
  pi.on("session_start", () => {
    cachedBoot = resolveBoot();
  });

  pi.on("before_agent_start", async (event) => {
    if (!cachedBoot) return;
    return {
      systemPrompt: event.systemPrompt + "\n\n" + cachedBoot,
    };
  });

  try {
    const mcp = await import("./mcp.ts");
    const ext = mcp.default || mcp;
    await ext(pi);
  } catch {
    // MCP bridge extension not available — non-fatal
  }

  try {
    const surface = await import("./surface.ts");
    const ext = surface.default || surface;
    await ext(pi);
  } catch {
    // Ambient-memory surface extension not available — non-fatal
  }
}
