// Generated by `doctrine boot install` — do not edit.

// Generated by `doctrine boot install` — do not edit.

/**
 * SL-263: doctrine ambient memory surfacing for pi.
 *
 * Maps pi's built-in tool calls onto doctrine's NEUTRAL wire and pipes the
 * envelope to `doctrine memory surface --input neutral --format plain` on the
 * child's stdin, appending the returned block to the tool result.
 *
 * Contractual properties (design SL-263 §5.7):
 *   - fail-open: every failure/timeout resolves to `undefined`, so the tool
 *     result is exactly what the tool produced;
 *   - bounded: an explicit timeout plus `ctx.signal`;
 *   - never blocks the event loop: an async spawn;
 *   - session dedup: `session_id` from `ctx.sessionManager`;
 *   - no subagent suppression: pi exposes no agent identity in `tool_result`.
 */

import { execFile } from "node:child_process";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

// ── BIN_PATH ──────────────────────────────────────────────────────────────────
// Baked at install time by `doctrine boot install`.

const BIN_PATH = "/nix/store/p4r89h46hvapyf300ab61312r4ha8a4z-doctrine-0.46.5/bin/doctrine";

/** A hook that outlives its nudge has already missed its moment. */
const SURFACE_TIMEOUT_MS = 5_000;

/** doctrine's neutral classes (src/memory.rs `CLASS_PATH` / `CLASS_COMMAND`). */
interface NeutralProbe {
  class: 'path' | 'command';
  value: string;
}

/** Map a pi tool call onto doctrine's neutral probe, or `undefined` if unmapped. */
function neutralProbe(toolName: string, input: unknown): NeutralProbe | undefined {
  const fields = (input ?? {}) as Record<string, unknown>;
  if (toolName === 'read' || toolName === 'edit' || toolName === 'write') {
    const value = fields.path;
    return typeof value === 'string' && value.length > 0
      ? { class: 'path', value }
      : undefined;
  }
  if (toolName === 'bash') {
    const value = fields.command;
    return typeof value === 'string' && value.length > 0
      ? { class: 'command', value }
      : undefined;
  }
  return undefined;
}

export default async function (pi: ExtensionAPI) {
  pi.on('tool_result', async (event, ctx) => {
    const probe = neutralProbe(event.toolName, event.input);
    if (!probe) return undefined;

    const envelope = JSON.stringify({
      session_id: ctx.sessionManager.getSessionId(),
      cwd: ctx.cwd,
      probe,
    });

    // The async `execFile` has no `input` option, so the envelope is written to
    // the child's stdin. The no-op `'error'` listener absorbs the EPIPE a child
    // that exits before draining stdin would otherwise raise as an unhandled
    // event, killing the pi process — the one outcome this extension forbids.
    const block = await new Promise<string>((resolve) => {
      const child = execFile(
        BIN_PATH,
        ['memory', 'surface', '--input', 'neutral', '--format', 'plain'],
        { timeout: SURFACE_TIMEOUT_MS, signal: ctx.signal },
        (err, stdout) => resolve(err ? '' : stdout),
      );
      child.stdin?.on('error', () => {});
      child.stdin?.end(envelope);
    });

    if (!block) return undefined;
    return {
      content: [...event.content, { type: 'text', text: block }],
    };
  });
}